language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIT6MGSAIM33ZQNLQ
  secret_access_key:
    secure: LNDi2SVnLB9Rjg+X5osXQEcGy+0wsEcGwcbil1U9I9y1W1FYu25T9Klme3UnkJVp2UCvrcM7Mv++QdyPHJEAM36wS1qxW3lfPDh1VTJE7QvB8pcSotgdrpVmVDpB63s8YBfrNrw5zSEx3fk32sgOldzH7C/GDCqNA4/PSWfHo8CoyNfcfCYcd7WTuOK14w0nmYmV21+rnaQ3z/3drfqMEm/6NFTvYDnTPAoRd7aWiLYEdXtY/OvaqmEs98SwaY8HPnVd8b1mJ56FML+z5QtguCB3mbyvuIRdjcOSLUTX8iz357KdkKy6QA8r8eaI48U9gqVcxjRFWRZjYwZj7noBvRPedXdoGNnod1YYLWmnA/AcqtC2+eGSJjfrR3b6EMQhGiPFPDvqKP3WyTj7n69QQUrA5GGSSAQ4y2Ze8uiRKPir5lCrSBxOShH0k/nlzNvqSxgWvxNKhN0uZc+vz3dGye23yZ9gf/mExivTP6yMlGdncaqdvd0u1zbcymbkb1GOXNzxJcMpZrljUVntEOjaq7TcHTrYNpUTAbysQ9S0WyYbNpp9p/tIANv4KkXBnquEAAt5c2A5U3URimJrjTznxBjlDNj7aJXLepX/on4b00O8cdMifY0ExirCbUnyOJvMi/U6bZ51E9AsDxiiFp7D5KEAfb9hTHQxdRGu4fXP7Lk=
  bucket: aws-website-sneakycrwcom-g7kgp
  local-dir: build
  skip_cleanup: true
  cache_control: "max-age=21600"
  on:
    repo: sneakycr0w/sneakycr0w.com
